# Generated by Django 6.0.3 on 2026-03-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'Inscription', 'verbose_name_plural': 'Inscriptions'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Eleve', 'verbose_name_plural': 'Eleves'},
        ),
        migrations.AlterModelOptions(
            name='studentparent',
            options={'verbose_name': "Responsable d'eleve", 'verbose_name_plural': "Responsables d'eleve"},
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('ENROLLED', 'Inscrit'), ('TRANSFERRED', 'Transfere'), ('DROPPED', 'Abandonne')], default='ENROLLED', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1),
        ),
        migrations.AlterField(
            model_name='studentparent',
            name='relationship',
            field=models.CharField(choices=[('FATHER', 'Pere'), ('MOTHER', 'Mere'), ('GUARDIAN', 'Tuteur')], max_length=20),
        ),
    ]
