# Generated by Django 6.0.3 on 2026-03-17 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_school_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name': 'Classe', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='gradelevel',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Niveau', 'verbose_name_plural': 'Niveaux'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'Ecole', 'verbose_name_plural': 'Ecoles'},
        ),
        migrations.AlterModelOptions(
            name='schoolsetting',
            options={'verbose_name': "Parametre d'ecole", 'verbose_name_plural': "Parametres d'ecole"},
        ),
        migrations.AlterModelOptions(
            name='schoolyear',
            options={'verbose_name': 'Annee scolaire', 'verbose_name_plural': 'Annees scolaires'},
        ),
        migrations.AlterModelOptions(
            name='term',
            options={'verbose_name': 'Periode', 'verbose_name_plural': 'Periodes'},
        ),
    ]
