# Generated by Django 6.0.3 on 2026-03-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashtransaction',
            options={'verbose_name': 'Transaction de caisse', 'verbose_name_plural': 'Transactions de caisse'},
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('VALIDATED', 'Validee'), ('CANCELLED', 'Annulee')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'Entree'), ('OUT', 'Sortie')], max_length=3),
        ),
    ]
