# Generated by Django 6.0.2 on 2026-02-12 23:43

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_schoolsetting'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Scolarité', max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('installments', models.PositiveIntegerField(default=10)),
                ('start_month', models.DateField(help_text='1er jour du mois de début (ex: 2026-09-01)')),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_plans', to='core.school')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_plans', to='core.schoolyear')),
            ],
        ),
        migrations.CreateModel(
            name='StudentFeeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_accounts', to='fees.feeplan')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_accounts', to='core.schoolyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_accounts', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'school_year')},
            },
        ),
        migrations.CreateModel(
            name='FeeInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_month', models.DateField(help_text='1er jour du mois (ex: 2026-09-01)')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_paid', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='fees.studentfeeaccount')),
            ],
            options={
                'ordering': ['due_month'],
                'unique_together': {('account', 'due_month')},
            },
        ),
    ]
