# Generated by Django 6.0.3 on 2026-03-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_studentfeeaccount_credit_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feeinstallment',
            options={'ordering': ['due_month'], 'verbose_name': 'Echeance', 'verbose_name_plural': 'Echeances'},
        ),
        migrations.AlterModelOptions(
            name='feeplan',
            options={'verbose_name': 'Plan de frais', 'verbose_name_plural': 'Plans de frais'},
        ),
        migrations.AlterModelOptions(
            name='studentfeeaccount',
            options={'verbose_name': 'Compte de frais eleve', 'verbose_name_plural': 'Comptes de frais eleve'},
        ),
        migrations.AlterField(
            model_name='feeplan',
            name='name',
            field=models.CharField(default='Scolarite', max_length=100),
        ),
        migrations.AlterField(
            model_name='feeplan',
            name='start_month',
            field=models.DateField(help_text='1er jour du mois de debut (ex: 2026-09-01)'),
        ),
    ]
