# Generated by Django 6.0.2 on 2026-02-08 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_schoolsetting'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanteenPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Forfait mensuel', max_length=100)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canteen_plans', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='CanteenAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('SERVED', 'Served'), ('NOT_SERVED', 'Not served')], default='SERVED', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canteen_attendance', to='core.schoolyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canteen_attendance', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'school_year', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CanteenSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Mettre le 1er jour du mois (ex: 2026-02-01)')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='canteen.canteenplan')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canteen_subscriptions', to='core.schoolyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canteen_subscriptions', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'school_year', 'month')},
            },
        ),
    ]
