# Generated by Django 6.0.3 on 2026-03-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='canteenattendance',
            options={'verbose_name': 'Passage cantine', 'verbose_name_plural': 'Passages cantine'},
        ),
        migrations.AlterModelOptions(
            name='canteenplan',
            options={'verbose_name': 'Forfait cantine', 'verbose_name_plural': 'Forfaits cantine'},
        ),
        migrations.AlterModelOptions(
            name='canteensubscription',
            options={'verbose_name': 'Abonnement cantine', 'verbose_name_plural': 'Abonnements cantine'},
        ),
        migrations.AlterField(
            model_name='canteenattendance',
            name='status',
            field=models.CharField(choices=[('SERVED', 'Servi'), ('NOT_SERVED', 'Non servi')], default='SERVED', max_length=12),
        ),
        migrations.AlterField(
            model_name='canteensubscription',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('PAID', 'Paye'), ('CANCELLED', 'Annule')], default='PENDING', max_length=10),
        ),
    ]
