# Generated by Django 6.0.2 on 2026-02-06 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('arrival_method', models.CharField(choices=[('MANUAL', 'Manuel'), ('FACIAL', 'Reconnaissance faciale')], default='MANUAL', max_length=10)),
                ('departure_method', models.CharField(choices=[('MANUAL', 'Manuel'), ('FACIAL', 'Reconnaissance faciale')], default='MANUAL', max_length=10)),
                ('status', models.CharField(choices=[('PRESENT', 'Présent'), ('LATE', 'En retard'), ('ABSENT', 'Absent'), ('EARLY_LEAVE', 'Sortie anticipée')], default='PRESENT', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.schoolyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'school_year', 'date')},
            },
        ),
    ]
