# Generated by Django 6.0.3 on 2026-03-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'Presence', 'verbose_name_plural': 'Presences'},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'En retard'), ('ABSENT', 'Absent'), ('EARLY_LEAVE', 'Sortie anticipee')], default='PRESENT', max_length=15),
        ),
    ]
